rawDataset <- read.table("household_power_consumption.txt", header = T, sep = ";", dec = ".",encoding = "UTF-8", stringsAsFactors = T, na.strings = "?")
na.omit(rawDataset)
dataSet1 <- subset(rawDataset, Date == "1/2/2007")
dataSet2 <- subset(rawDataset, Date == "2/2/2007")
dataset <- rbind(dataSet1, dataSet2)
dataset$Date <- as.Date(dataset$Date, format("%d/%m/%y"))
dataset$Time <- strptime(dataset$Time, format = ("%H:%M:%S"))
dataset[1:1440,"Time"] <- format(dataset[1:1440,"Time"],"2007-02-01 %H:%M:%S")
dataset[1441:2880,"Time"] <- format(dataset[1441:2880,"Time"],"2007-02-02 %H:%M:%S")
png(filename = "plot3.png", width = 480, height = 480)
plot(dataset$Time, dataset$Sub_metering_1, type = "n", xlab = "", ylab = "Energy sub metering")
with(dataset, lines(Time, Sub_metering_1))
with(dataset, lines(Time, Sub_metering_2, col = "red"))
with(dataset, lines(Time, Sub_metering_3, col = "blue"))
legend("topright", lty = 1, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
title(main="Energy sub-metering")
dev.off()
